version: '3.8'
services:
  db:
    container_name: db
    image: mysql:8.0.27
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
  nginx:
    container_name: nginx
    build: ./docker/nginx
    command: nginx -g "daemon off;"
    links:
      - php
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/logs/nginx:/var/log/nginx
      - ./server:/var/www/html
  php:
    container_name: php
    build: ./docker/php
    ports:
      - "9000:9000"
    links:
      - db
    volumes:
      - ./server:/var/www/html
    working_dir: /var/www/html
